MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: './checkpoints/jx_vit_base_p16_224-80ecf9dd.pth'
  # PRETRAIN_PATH: './checkpoints/resnet50-11ad3fa6.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('6')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [16, 16]
  Evaluate: "StandardSetting"  # ClothChangingSetting or StandardSetting
  ATTR: True #False #True  # ADDED
  PAR_MODEL: "densenet121" #"resnet50"
  PAR_DATASET: "duke" #"market"

INPUT:
  SIZE_TRAIN: [256, 128] #[224, 224] #[256, 128]
  SIZE_TEST: [256, 128] #[224, 224] #[256, 128][256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  # PIXEL_MEAN: [0.485, 0.456, 0.406]
  # PIXEL_STD: [0.229, 0.224, 0.225]
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('nkup')
  ROOT_DIR: ('./data')

DATALOADER:
  SAMPLER: 'bce_triplet' #'bce_triplet' #'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 150
  BASE_LR: 0.0035 #0.008
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 50
  EVAL_PERIOD: 1
  WEIGHT_DECAY:  5e-4 #1e-4
  WEIGHT_DECAY_BIAS: 5e-4 #1e-4
  BIAS_LR_FACTOR: 1 #2

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  # WEIGHT: './logs/session3_swin/nkup/updated_RE/base/sc/best_checkout.pth'
  # WEIGHT: './logs/session2/nkup/updated_RE/base/sc/best_checkout.pth'
  WEIGHT: './logs/session1/nkup/original_RE/base_updated_metric/sc/best_checkout.pth'
  # WEIGHT: './logs/session1/nkup/original_RE/base/sc/best_checkout.pth'
  # WEIGHT: './logs/session1/nkup/updated_RE/base/sc/best_checkout.pth'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

# OUTPUT_DIR: './logs/session3_swin/nkup/updated_RE/base/sc/'
# OUTPUT_DIR: './logs/session2/nkup/updated_RE/base/sc/'
OUTPUT_DIR: './logs/session1/nkup/original_RE/base_updated_metric/sc/'
# OUTPUT_DIR: './logs/session1/nkup/original_RE/base/sc/'
# OUTPUT_DIR: './logs/session1/nkup/updated_RE/base/sc/'